### ISSUE TITLE
FONT.GRB is opened with NHACP_O_RDWR, should be NHACP_O_RDONLY

### ISSUE THREAD

**Issue by thorpej** [tergav17/IshkurCPM#5]
Debug trace from nabud:

DEBUG: nhacp_req_storage_open: [::ffff:127.0.0.1] nhacp_o_flags 0x0001 -> fileio_o_flags 0x00000041
INFO: stext_file_open: [::ffff:127.0.0.1] Opening 'FONT.GRB'
ERROR: stext_file_open: [::ffff:127.0.0.1] Unable to open file 'FONT.GRB': Permission denied

This obviously makes the boot fail if the Ishkur system binaries are installed into the host system as read-only.

**Comment by thorpej** [comment]
This issues also applies to loading the CCP.

**Comment by tergav17** [comment]
Fixed, thank you!
